version: 2.0
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2
    steps:
      - checkout
      - run:
          name: Run Build Script
          command: ./build.sh
workflows:
  version: 2
  build:
    jobs:
      - build:
          context: repo-version-secrets
